---
title: "Generating COVID data"
---
```{r,include=FALSE}
library(plyr)
library(imputeTS)
library(dplyr)
library(tidyverse)
library(forcats)
library(stringr)
library(base)
library(sf)
library(scales)
library(lubridate)
library(aTSA)
library(tseries)
library(forecast)
library(CADFtest)
library(vars)
library(urca)
library(lattice)
library(urca)
library(ggplot2)
library(MASS)
```

# read data files
```{r}
train=read.csv('training_data.csv')
test=read.csv('test_data.csv')
```

# data exploratory
```{r}
pairs(train[, 2:6])

cor(train[, 2:12])
# hospital admission and humidity, hospital admission and precipitation have small correlation less than 0.1
#hospital admission and new deaths, hospital admission and resident are highly positive correlated 
#hospital admission and temperature, hospital admission and transit are highly negative correlated

#icu admission and humidity, icu admission and precipitation, icu and wind speed have small correlation less than 0.1.
#icu admission and new deaths, icu admission and stringency, icu admission and resident are highly positive correlated 
#icu admission and temperature, icu admission and transit are highly negative correlated

# for hospital admission: fit var model including all variables, comparing to the var model without humidity, precipitation.

# for icu admission: fit var model including all variables, comparing to the var model without humidity, precipitation and wind speed.
```

# creating time series
```{r}
icu.ts=ts(train$icu, start=c(2021), frequency = 52)
hosp.ts=ts(train$hospital, start=c(2021), frequency = 52)
cases.ts=ts(train$newcases, start=c(2021), frequency = 52)
deaths.ts=ts(train$newdeaths, start=c(2021), frequency = 52)
stringency.ts=ts(train$stringency, start=c(2021), frequency = 52)
transit.ts=ts(train$transit, start=c(2021), frequency = 52)
resident.ts=ts(train$resident, start=c(2020), frequency=52)
temp.ts=ts(train$temperature, start=c(2021), frequency = 52)
precip.ts=ts(train$precipitation, start=c(2021), frequency = 52)
wind.ts=ts(train$windspeed, start=c(2021), frequency = 52)
humidity.ts=ts(train$humidity, start=c(2021), frequency = 52)

autoplot(temp.ts)
max.lag<-round(sqrt(length(m1.d$hospital_adm))) #18
CADFtest(temp.ts, type= "trend", criterion= "BIC", max.lag.y=max.lag)
```

# linear model
```{r}
lm1=lm(hospital~., data=train[,c(2,3,5,6,7,8,9,10,11,12)])
summary(lm1)
# linear model suggests new deaths, temperature and humidity have impact on hospital admission
```

# Hospital admission VAR model
The VAR model selects lag=1, which means the values of factors in week t-1 have impact on value in week t of the response.
```{r}
################### full model 
m1=train[, c(5,2,3,6,7,8,9,10,11,12)]
m1.d=data.frame(diff(m1))

VARselect(m1,type="const", lag.max=10)
fit_var1<-VAR(m1,type="const",p=3) 
summary(fit_var1)
colnames(m1)
causality(fit_var1, cause=colnames(m1)[2:10])
pred_var <- predict(fit_var1, n.ahead = 4, ci= 0.95)
hosp_forecast<-ts(pred_var$fcst$hospital[,1],start=2022)
hosp_forecast

######################### model without humidity and precipitation, based on the correlation result
m2<-train[, c(5,2,3,6,7,10,11,12)]
VARselect(m2,type="const", lag.max=10)
fit_var2<-VAR(m2,type="const",p=4) 
summary(fit_var2)

causality(fit_var2, cause=colnames(m2)[2:8])
pred_var2 <- predict(fit_var2, n.ahead = 4, ci= 0.95)
hosp_forecast2<-ts(pred_var2$fcst$hospital[,1],start=2022)
hosp_forecast2

######################## using significant variables from linear model
m3<-train[, c(5,3,7,8)]
VARselect(m3,type="const", lag.max=10)
fit_var3<-VAR(m3,type="const",p=2) 
summary(fit_var3)

causality(fit_var3, cause=colnames(m3)[2:4])
pred_var3<- predict(fit_var3, n.ahead = 4, ci= 0.95)
hosp_forecast3<-ts(pred_var3$fcst$hospital[,1],start=2022)
hosp_forecast3
```

# computing model errors
```{r}
mape=function(test, forecast, n){
  mape1=sum(abs(((test-forecast)/test)*100))/n
  return(mape1)
}

mse=function(test, forecast, n){
  mse1=sum((test-forecast)^2)/n
  return(mse1)
}

rmse=function(test, forecast, n){
  rmse1=sqrt(sum((test-forecast)^2)/n)
  return(rmse1)
}

mae=function(test, forecast, n){
  mae1=sum(abs((test-forecast)))/n
  return(mae1)
}
```

# comparing models for hospital admission
```{r}
mse1=mse(test[67:70, 5], hosp_forecast, 4)
mse2=mse(test[67:70, 5], hosp_forecast2, 4)
mse3=mse(test[67:70, 5], hosp_forecast3, 4)

rmse1=rmse(test[67:70, 5], hosp_forecast, 4)
rmse2=rmse(test[67:70, 5], hosp_forecast2, 4)
rmse3=rmse(test[67:70, 5], hosp_forecast3, 4)

mae1=mae(test[67:70, 5], hosp_forecast, 4)
mae2=mae(test[67:70, 5], hosp_forecast2, 4)
mae3=mae(test[67:70, 5], hosp_forecast3, 4)

mape1=mape(test[67:70, 5], hosp_forecast, 4)
mape2=mape(test[67:70, 5], hosp_forecast2, 4)
mape3=mape(test[67:70, 5], hosp_forecast3, 4)

c(AIC(fit_var1), AIC(fit_var2), AIC(fit_var3))
c(mape1,mape2, mape3)
c(mse1, mse2, mse3)
c(rmse1, rmse2, rmse3)
c(mae1, mae2, mae3)
# comparing full model (m1) and model without humidity and precipitation (m2), the errors and AIC suggest m2 performs better.
```

